@host=http://localhost:5149
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiODQ4MzhjNy01YjRhLTQ5N2QtYTE1Yy02OWVhNjA3YjcwNjciLCJnaXZlbl9uYW1lIjoiWWVya2VidWxhbiIsImZhbWlseV9uYW1lIjoiU2VyaWtiYXlldiIsImp0aSI6IjUyYWE3NmY0LTY1MDItNGI0MS1hZDJkLTE2ZmMyOTExOGIwNyIsImV4cCI6MTY5NDg5Mzg2OCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.bnzj70P2TcOO4t8ZUxuajIXHdIhw3RvQsSPjblRof5I
@hostId=f53bc4b8-edb4-4a18-aab7-d9a78f0edfd5

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Yummy menu",
  "description": "A menu with yummy food",
  "sections": [
    {
      "name": "Appetizers",
      "description": "Starters",
      "items": [{
        "name": "Fried Pickles",
        "description": "Deep fried pickles"
      }]
    }
  ]
}