@host=http://localhost:5149
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkOThlYWViMi05YTE4LTRiYTgtOWQzMy0wMGNlMzY2MTIzMDgiLCJnaXZlbl9uYW1lIjoiWWVya2VidWxhbiIsImZhbWlseV9uYW1lIjoiU2VyaWtiYXlldiIsImp0aSI6IjZjMzg2ZmZkLTI0NTEtNDcyMy04MTQ2LWE5NTljNWU4OTBmMyIsImV4cCI6MTY5NDE1NjA2OSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.ItBG4yEoKsaJBwKYqkr8l1TlK8NoFvckDJob59MSXBA

GET {{host}}/dinners
Authorization: Bearer {{token}}